services:
  - type: web
    name: gps-funcionarios-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    buildFilter:
      paths:
        - "**/*"
    envVars:
      - key: ADMIN_PASSWORD
        value: GPS@Orlando2026
      - key: PORT
        value: "10000"
